# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 10:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(default='password', max_length=100)),
                ('inserted_on', models.DateTimeField(auto_now_add=True, verbose_name='Record inserted on')),
            ],
            options={
                'ordering': ('company_name',),
            },
        ),
        migrations.CreateModel(
            name='login_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mcq_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='question_bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=50)),
                ('choice1', models.CharField(max_length=50)),
                ('choice2', models.CharField(max_length=50)),
                ('choice3', models.CharField(max_length=50)),
                ('inserted_on', models.DateField(auto_now_add=True, verbose_name='Record inserted on')),
            ],
            options={
                'ordering': ('inserted_on', 'training'),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(default='male', max_length=6)),
                ('college', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('graduation_year', models.IntegerField(default=2018)),
                ('mobile', models.IntegerField()),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('inserted_on', models.DateTimeField(auto_now_add=True, verbose_name='Record inserted on')),
                ('login_credential', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('inserted_on', models.DateField(auto_now_add=True, verbose_name='Record inserted on')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student')),
            ],
            options={
                'ordering': ('inserted_on',),
            },
        ),
        migrations.CreateModel(
            name='studentFeedbackChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='studentFeedbackOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentFeedbackChoice')),
            ],
        ),
        migrations.CreateModel(
            name='studentFeedbackQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_question', models.CharField(max_length=100)),
                ('inserted_on', models.DateField(auto_now_add=True, verbose_name='Record inserted on')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('eligibility', models.CharField(blank=True, max_length=300)),
                ('company_name', models.CharField(default='Unnamed', max_length=100)),
                ('start_date', models.DateField(verbose_name='Training Start Date')),
                ('duration', models.CharField(max_length=50)),
                ('stipend', models.IntegerField(blank=True)),
                ('deadline', models.DateField(verbose_name='Application Deadline')),
                ('applicants_count', models.IntegerField(default=0)),
                ('category', models.CharField(default='production', max_length=100)),
                ('inserted_on', models.DateField(auto_now_add=True, verbose_name='Record inserted on')),
                ('status', models.CharField(default='under review', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
            options={
                'ordering': ('inserted_on',),
            },
        ),
        migrations.AddField(
            model_name='studentfeedbackoptions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentFeedbackQuestions'),
        ),
        migrations.AddField(
            model_name='studentfeedbackoptions',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
        migrations.AddField(
            model_name='studentfeedbackchoice',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentFeedbackQuestions'),
        ),
        migrations.AddField(
            model_name='studentapplications',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TrainingProgram'),
        ),
        migrations.AddField(
            model_name='question_bank',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TrainingProgram'),
        ),
        migrations.AddField(
            model_name='mcq_result',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question_bank'),
        ),
        migrations.AddField(
            model_name='mcq_result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
    ]
